export type Quest = {
  id: string;
  npc: string;
  world: number;
  name: string;
};

const QuestsW1: Array<Quest> = [
  {
    id: "TP Pete1",
    npc: "TP Pete",
    world: 1,
    name: "Roll of Anger",
  },
  {
    id: "TP Pete2",
    npc: "TP Pete",
    world: 1,
    name: "The Rats are to Blame!",
  },
  {
    id: "TP Pete3",
    npc: "TP Pete",
    world: 1,
    name: "Fired for BS Reasons!",
  },
  {
    id: "Sprout1",
    npc: "Sprout",
    world: 1,
    name: "Sticks and Stone Something Something Bones...",
  },
  {
    id: "Sprout2",
    npc: "Sprout",
    world: 1,
    name: "Justice Wears No Clothes",
  },
  {
    id: "Sprout3",
    npc: "Sprout",
    world: 1,
    name: "Shoe Shopping with Sprout",
  },
  {
    id: "Sprout4",
    npc: "Sprout",
    world: 1,
    name: "Frisbee Fanatic",
  },
  {
    id: "Town Marble1",
    npc: "Town Marble",
    world: 1,
    name: "Visualizing the Sculpture Within...",
  },
  {
    id: "Woodsman1",
    npc: "Woodsman",
    world: 1,
    name: "A noob's first swing",
  },
  {
    id: "Woodsman2",
    npc: "Woodsman",
    world: 1,
    name: "A noob's 2nd first swing",
  },
  {
    id: "Woodsman3",
    npc: "Woodsman",
    world: 1,
    name: "It's Just a Plank, Bro!",
  },
  {
    id: "Woodsman4",
    npc: "Woodsman",
    world: 1,
    name: "Exotic Pranks... I mean Logs!",
  },
  {
    id: "Scripticus2",
    npc: "Scripticus",
    world: 1,
    name: "Hardcore Gamer Status, Here I Come!",
  },
  {
    id: "Scripticus3",
    npc: "Scripticus",
    world: 1,
    name: "Gear Up, Gamer!",
  },
  {
    id: "Scripticus4",
    npc: "Scripticus",
    world: 1,
    name: "Mr. Worldwide",
  },
  {
    id: "Scripticus5",
    npc: "Scripticus",
    world: 1,
    name: "The Choice is Yours!",
  },
  {
    id: "Scripticus6",
    npc: "Scripticus",
    world: 1,
    name: "Certified Swinger, of Pickaxes of course!",
  },
  {
    id: "Scripticus7",
    npc: "Scripticus",
    world: 1,
    name: "The Smithing Grind",
  },
  {
    id: "Scripticus8",
    npc: "Scripticus",
    world: 1,
    name: "The Unoccupied Picnic",
  },
  {
    id: "Scripticus9",
    npc: "Scripticus",
    world: 1,
    name: "Seeking Foreign Aid",
  },
  {
    id: "Scripticus10",
    npc: "Scripticus",
    world: 1,
    name: "What Lies at the Heart of the Forest",
  },
  {
    id: "Scripticus11",
    npc: "Scripticus",
    world: 1,
    name: "The Bigger they are, the Bigger they Fall!",
  },
  {
    id: "Scripticus12",
    npc: "Scripticus",
    world: 1,
    name: "Champion of the Grasslands",
  },
  {
    id: "Scripticus13",
    npc: "Scripticus",
    world: 1,
    name: "Can't somebody else do it?",
  },
  {
    id: "Krunk1",
    npc: "Krunk",
    world: 1,
    name: "A Plot to be Perfect",
  },
  {
    id: "Krunk2",
    npc: "Krunk",
    world: 1,
    name: "The Scientific Method, According to a Rock",
  },
  {
    id: "Krunk3",
    npc: "Krunk",
    world: 1,
    name: "King of the Cavern",
  },
  {
    id: "Glumlee1",
    npc: "Glumlee",
    world: 1,
    name: "Learning to Swing",
  },
  {
    id: "Glumlee2",
    npc: "Glumlee",
    world: 1,
    name: "Learning to Smelt",
  },
  {
    id: "Glumlee3",
    npc: "Glumlee",
    world: 1,
    name: "Literally Burning your Money",
  },
  {
    id: "Glumlee4",
    npc: "Glumlee",
    world: 1,
    name: "The Impossible Task",
  },
  {
    id: "Glumlee5",
    npc: "Glumlee",
    world: 1,
    name: "He's Havin' a Bad Day",
  },
  {
    id: "Picnic Stowaway1",
    npc: "Picnic Stowaway",
    world: 1,
    name: "The Hungry Stowaway",
  },
  {
    id: "Picnic Stowaway2",
    npc: "Picnic Stowaway",
    world: 1,
    name: "Beating Up Frogs for some Sauce",
  },
  {
    id: "Picnic Stowaway3",
    npc: "Picnic Stowaway",
    world: 1,
    name: "Live-Action Entertainment",
  },
  {
    id: "Picnic Stowaway4",
    npc: "Picnic Stowaway",
    world: 1,
    name: "The Most Important Meal of the Day",
  },
  {
    id: "Picnic Stowaway5",
    npc: "Picnic Stowaway",
    world: 1,
    name: "Brunchin' with the Blobs",
  },
  {
    id: "Picnic Stowaway6",
    npc: "Picnic Stowaway",
    world: 1,
    name: "Luncheon with the Inlaws",
  },
  {
    id: "Picnic Stowaway7",
    npc: "Picnic Stowaway",
    world: 1,
    name: "Afternoon Tea in a Jiffy",
  },
  {
    id: "Picnic Stowaway8",
    npc: "Picnic Stowaway",
    world: 1,
    name: "Early Evening Eating Endeavor",
  },
  {
    id: "Picnic Stowaway9",
    npc: "Picnic Stowaway",
    world: 1,
    name: "The Last Supper, at Least for Today!",
  },
  {
    id: "Picnic Stowaway10",
    npc: "Picnic Stowaway",
    world: 1,
    name: "Don't Desert the Dessert",
  },
  {
    id: "Picnic Stowaway11",
    npc: "Picnic Stowaway",
    world: 1,
    name: "A Midnight Snack",
  },
  {
    id: "Picnic Stowaway12",
    npc: "Picnic Stowaway",
    world: 1,
    name: "King of Food",
  },
  {
    id: "Hamish1",
    npc: "Hamish",
    world: 1,
    name: "The Hamazing Plot Twist",
  },
  {
    id: "Hamish2",
    npc: "Hamish",
    world: 1,
    name: "Should We Tell Him?",
  },
  {
    id: "Hamish3",
    npc: "Hamish",
    world: 1,
    name: "Slime for Storage",
  },
  {
    id: "Mr Pigibank1",
    npc: "Mr Pigibank",
    world: 1,
    name: "A Pig and his Stamps",
  },
  {
    id: "Promotheus1",
    npc: "Promotheus",
    world: 1,
    name: "I'm Ready, Promotion!",
  },
  {
    id: "Promotheus2",
    npc: "Promotheus",
    world: 1,
    name: "Three Right Answers",
  },
  {
    id: "Promotheus3",
    npc: "Promotheus",
    world: 1,
    name: "Slovakian Scare",
  },
  {
    id: "Promotheus4",
    npc: "Promotheus",
    world: 1,
    name: "The Witcher, but not Really",
  },
  {
    id: "Bushlyte1",
    npc: "Bushlyte",
    world: 1,
    name: "A Peanut for your Thoughts",
  },
  {
    id: "Bushlyte2",
    npc: "Bushlyte",
    world: 1,
    name: "Honk if you Love Peanuts!",
  },
  {
    id: "Bushlyte3",
    npc: "Bushlyte",
    world: 1,
    name: "A Peanut Saved is a Peanut not Eaten!",
  },
  {
    id: "Rocklyte1",
    npc: "Rocklyte",
    world: 1,
    name: "How It's Made, Episode 7. The Super Peanut",
  },
  {
    id: "Rocklyte2",
    npc: "Rocklyte",
    world: 1,
    name: "If Life Gives you Peanuts, make Shiny Peanuts!",
  },
  {
    id: "Rocklyte3",
    npc: "Rocklyte",
    world: 1,
    name: "Becoming the Best Beginner",
  },
  {
    id: "Stiltzcho1",
    npc: "Stiltzcho",
    world: 1,
    name: "Outta the Way Slimes",
  },
  {
    id: "Stiltzcho2",
    npc: "Stiltzcho",
    world: 1,
    name: "No Stone Unturned",
  },
  {
    id: "Stiltzcho3",
    npc: "Stiltzcho",
    world: 1,
    name: "Investigator by Day, Prankster by Night",
  },
  {
    id: "Stiltzcho4",
    npc: "Stiltzcho",
    world: 1,
    name: "Time Crime Episode 1",
  },
  {
    id: "Stiltzcho5",
    npc: "Stiltzcho",
    world: 1,
    name: "Time Crime Episode 2",
  },
  {
    id: "Stiltzcho6",
    npc: "Stiltzcho",
    world: 1,
    name: "Time Crime Season Finale",
  },
  {
    id: "Funguy1",
    npc: "Funguy",
    world: 1,
    name: "Mushroom Munchies",
  },
  {
    id: "Funguy2",
    npc: "Funguy",
    world: 1,
    name: "Videogame Highscores are COOL!",
  },
  {
    id: "Funguy3",
    npc: "Funguy",
    world: 1,
    name: "Partycrastination",
  },
  {
    id: "Funguy4",
    npc: "Funguy",
    world: 1,
    name: "Party Crashin'",
  },
  {
    id: "Funguy5",
    npc: "Funguy",
    world: 1,
    name: "Wicked Party Cleanup",
  },
  {
    id: "Tiki Chief1",
    npc: "Tiki Chief",
    world: 1,
    name: "Brochure Building",
  },
  {
    id: "Tiki Chief2",
    npc: "Tiki Chief",
    world: 1,
    name: "Three Strikes, you're Out!",
  },
  {
    id: "Tiki Chief3",
    npc: "Tiki Chief",
    world: 1,
    name: "Blame it on the Glublins",
  },
  {
    id: "Tiki Chief4",
    npc: "Tiki Chief",
    world: 1,
    name: "Hotel? Tikivago. Sorry, couldn't Help It!",
  },
  {
    id: "Dog Bone1",
    npc: "Dog Bone (NPC)",
    world: 1,
    name: "Why he Die???",
  },
  {
    id: "Dog Bone2",
    npc: "Dog Bone (NPC)",
    world: 1,
    name: "Bow Wow going Dow..n!",
  },
  {
    id: "Builder Bird1",
    npc: "Builder Bird",
    world: 1,
    name: "Restoring Power to the Portal",
  },
  {
    id: "Papua Piggea1",
    npc: "Papua Piggea",
    world: 1,
    name: "Oinko Boinko",
  },
  {
    id: "Papua Piggea2",
    npc: "Papua Piggea",
    world: 1,
    name: "Crystal Crime Stopper",
  },
  {
    id: "Papua Piggea3",
    npc: "Papua Piggea",
    world: 1,
    name: "Stamp Collecting",
  },
  {
    id: "Papua Piggea4",
    npc: "Papua Piggea",
    world: 1,
    name: "This Little Piggy Felt Remorse",
  },
  {
    id: "Mutton1",
    npc: "Mutton",
    world: 1,
    name: "Beatboxing Starterpack",
  },
  {
    id: "Mutton2",
    npc: "Mutton",
    world: 1,
    name: "Clout Chasin'",
  },
  {
    id: "Mutton3",
    npc: "Mutton",
    world: 1,
    name: "Cross Platform Promotion",
  },
  {
    id: "Mutton4",
    npc: "Mutton",
    world: 1,
    name: "7 Figure Followers",
  },
  {
    id: "Meel1",
    npc: "Meel",
    world: 1,
    name: "Spooky Scary Skelepoops",
  },
  {
    id: "Meel2",
    npc: "Meel",
    world: 1,
    name: "Waitin' for the Cards to Drop",
  },
  {
    id: "Dazey1",
    npc: "Dazey",
    world: 1,
    name: "Dressing like a Dork",
  },
  {
    id: "Dazey2",
    npc: "Dazey",
    world: 1,
    name: "Literally Physics",
  },
  {
    id: "Giftmas Blobulyte1",
    npc: "Giftmas Blobulyte",
    world: 1,
    name: "Boo, Headshot!",
  },
  {
    id: "Giftmas Blobulyte2",
    npc: "Giftmas Blobulyte",
    world: 1,
    name: "You Shouldn't Have! No, really.",
  },
  {
    id: "Telescope1",
    npc: "Telescope",
    world: 1,
    name: "I'm Seeing Stars!",
  },
  {
    id: "Loveulyte1",
    npc: "Loveulyte",
    world: 1,
    name: "Heart Hogger",
  },
  {
    id: "Loveulyte2",
    npc: "Loveulyte",
    world: 1,
    name: "Heartbreaker",
  },
  {
    id: "Egggulyte1",
    npc: "Egggulyte",
    world: 1,
    name: "Egg Shaped Lootboxes!",
  },
  {
    id: "Egggulyte2",
    npc: "Egggulyte",
    world: 1,
    name: "I've Got a Golden Tickegg!",
  },
  {
    id: "Coastiolyte1",
    npc: "Coastiolyte",
    world: 1,
    name: "Cooler than a Cooler!",
  },
  {
    id: "Coastiolyte2",
    npc: "Coastiolyte",
    world: 1,
    name: "Vibe Check",
  },
  {
    id: "Toadstall1",
    npc: "Toadstall",
    world: 1,
    name: "Creating a Party!",
  },
  {
    id: "Toadstall2",
    npc: "Toadstall",
    world: 1,
    name: "Bigger Party Better Party!",
  },
  {
    id: "Toadstall3",
    npc: "Toadstall",
    world: 1,
    name: "Bother the Frogger!",
  },
  {
    id: "Falloween Pumpkin1",
    npc: "Falloween Pumpkin",
    world: 1,
    name: "The Spookyness",
  },
  {
    id: "Falloween Pumpkin2",
    npc: "Falloween Pumpkin",
    world: 1,
    name: "The Scaryness",
  },
  {
    id: "Falloween Pumpkin3",
    npc: "Falloween Pumpkin",
    world: 1,
    name: "The Horroriness",
  },
  {
    id: "Falloween Pumpkin4",
    npc: "Falloween Pumpkin",
    world: 1,
    name: "The Booeyness",
  },
  {
    id: "Falloween Pumpkin5",
    npc: "Falloween Pumpkin",
    world: 1,
    name: "The Afterparty",
  },
];

const QuestsW2: Array<Quest> = [
  {
    id: "Cactolyte1",
    npc: "Cactolyte",
    world: 2,
    name: "Super Skillage",
  },
  {
    id: "Cactolyte2",
    npc: "Cactolyte",
    world: 2,
    name: "Top Skillage",
  },
  {
    id: "Cactolyte3",
    npc: "Cactolyte",
    world: 2,
    name: "Peanut De-Aging",
  },
  {
    id: "Cactolyte4",
    npc: "Cactolyte",
    world: 2,
    name: "Maestro! The Stro! Mman!",
  },
  {
    id: "Constructor Crow1",
    npc: "Constructor Crow",
    world: 2,
    name: "Restoring Power to another Portal",
  },
  {
    id: "Speccius1",
    npc: "Speccius",
    world: 2,
    name: "More like 'Sleepius' lmao",
  },
  {
    id: "Speccius2",
    npc: "Speccius",
    world: 2,
    name: "Specialization Station",
  },
  {
    id: "Fishpaste971",
    npc: "Fishpaste97",
    world: 2,
    name: "'Accidental' Exploit",
  },
  {
    id: "Fishpaste972",
    npc: "Fishpaste97",
    world: 2,
    name: "Can you do the Can Can?",
  },
  {
    id: "Scubidew1",
    npc: "Scubidew",
    world: 2,
    name: "Don't Step to Me, Bro!",
  },
  {
    id: "Scubidew2",
    npc: "Scubidew",
    world: 2,
    name: "Uncovering the Deep Sea State!!!",
  },
  {
    id: "Scubidew3",
    npc: "Scubidew",
    world: 2,
    name: "A Normal Quest.",
  },
  {
    id: "Whattso1",
    npc: "Whattso",
    world: 2,
    name: "Mopey Dick",
  },
  {
    id: "Whattso2",
    npc: "Whattso",
    world: 2,
    name: "The Whaley Hard Minigame",
  },
  {
    id: "Whattso3",
    npc: "Whattso",
    world: 2,
    name: "Bobbin' Bobbers",
  },
  {
    id: "Whattso4",
    npc: "Whattso",
    world: 2,
    name: "The Biggest Fish in the Sea...?",
  },
  {
    id: "Postboy Pablob1",
    npc: "Postboy Pablob",
    world: 2,
    name: "Signed, Sealed and Lost in the Post",
  },
  {
    id: "Bandit Bob1",
    npc: "Bandit Bob",
    world: 2,
    name: "Bullets for Bandit Bob!",
  },
  {
    id: "Bandit Bob2",
    npc: "Bandit Bob",
    world: 2,
    name: "Bob's Brand New Bandana",
  },
  {
    id: "Bandit Bob3",
    npc: "Bandit Bob",
    world: 2,
    name: "Bringing Bob's Boxes",
  },
  {
    id: "Bandit Bob4",
    npc: "Bandit Bob",
    world: 2,
    name: "The Desert Dungeon Prequest",
  },
  {
    id: "Carpetiem1",
    npc: "Carpetiem",
    world: 2,
    name: "Darn Lazy Gamers!",
  },
  {
    id: "Carpetiem2",
    npc: "Carpetiem",
    world: 2,
    name: "Old Timey Craftin'",
  },
  {
    id: "Carpetiem3",
    npc: "Carpetiem",
    world: 2,
    name: "Be like Buster!",
  },
  {
    id: "Carpetiem4",
    npc: "Carpetiem",
    world: 2,
    name: "Helping 100 times over",
  },
  {
    id: "Djonnut1",
    npc: "Djonnut",
    world: 2,
    name: "Genie Dieting",
  },
  {
    id: "Djonnut2",
    npc: "Djonnut",
    world: 2,
    name: "I'm Blue Dabadedada",
  },
  {
    id: "Djonnut3",
    npc: "Djonnut",
    world: 2,
    name: "The Blue New World",
  },
  {
    id: "Goldric1",
    npc: "Goldric",
    world: 2,
    name: "Trickle Down Economics",
  },
  {
    id: "Goldric2",
    npc: "Goldric",
    world: 2,
    name: "Hoopsies",
  },
  {
    id: "Goldric3",
    npc: "Goldric",
    world: 2,
    name: "Only Winners have Portraits",
  },
  {
    id: "Goldric4",
    npc: "Goldric",
    world: 2,
    name: "Criminal Code of Conduct",
  },
  {
    id: "Goldric5",
    npc: "Goldric",
    world: 2,
    name: "Dress to Impress",
  },
  {
    id: "Goldric6",
    npc: "Goldric",
    world: 2,
    name: "Dont lay a finger on my Sheepies!!!",
  },
  {
    id: "Snake Jar1",
    npc: "Snake Jar",
    world: 2,
    name: "Lookin' Like a Snack",
  },
  {
    id: "Snake Jar2",
    npc: "Snake Jar",
    world: 2,
    name: "Red Stuff Bad!",
  },
  {
    id: "Snake Jar3",
    npc: "Snake Jar",
    world: 2,
    name: "PSA. You Are Being Eaten!",
  },
  {
    id: "Snake Jar4",
    npc: "Snake Jar",
    world: 2,
    name: "A Noob, served Medium Rare!",
  },
  {
    id: "Loominadi1",
    npc: "Loominadi",
    world: 2,
    name: "Rhyming is Key!",
  },
  {
    id: "Loominadi2",
    npc: "Loominadi",
    world: 2,
    name: "Uh, Something About Vials?",
  },
  {
    id: "Loominadi3",
    npc: "Loominadi",
    world: 2,
    name: "Journey to the Center of the Blundermines",
  },
  {
    id: "Loominadi4",
    npc: "Loominadi",
    world: 2,
    name: "The Mummy of Mystery",
  },
  {
    id: "Cowbo Jones1",
    npc: "Cowbo Jones",
    world: 2,
    name: "The Grind Begins...?",
  },
  {
    id: "Cowbo Jones2",
    npc: "Cowbo Jones",
    world: 2,
    name: "The Hatless Howerhouse!",
  },
  {
    id: "Cowbo Jones3",
    npc: "Cowbo Jones",
    world: 2,
    name: "No Country for One Character",
  },
  {
    id: "Cowbo Jones4",
    npc: "Cowbo Jones",
    world: 2,
    name: "Say Goodbye to your Dubloon!",
  },
  {
    id: "Cowbo Jones5",
    npc: "Cowbo Jones",
    world: 2,
    name: "Alchemial Apprentice",
  },
  {
    id: "Cowbo Jones6",
    npc: "Cowbo Jones",
    world: 2,
    name: "Three Vials? Those are Rookie Numbers!",
  },
  {
    id: "Cowbo Jones7",
    npc: "Cowbo Jones",
    world: 2,
    name: "The Notorious B.O.B",
  },
  {
    id: "Cowbo Jones8",
    npc: "Cowbo Jones",
    world: 2,
    name: "Bake Him Away, Toys",
  },
  {
    id: "Cowbo Jones9",
    npc: "Cowbo Jones",
    world: 2,
    name: "A Hat in Crime",
  },
  {
    id: "Cowbo Jones10",
    npc: "Cowbo Jones",
    world: 2,
    name: "Commence Criminal Crimes!",
  },
  {
    id: "Cowbo Jones11",
    npc: "Cowbo Jones",
    world: 2,
    name: "The Worst Trade Deal in History",
  },
  {
    id: "Cowbo Jones12",
    npc: "Cowbo Jones",
    world: 2,
    name: "Children? What'd they ever do for Me...",
  },
  {
    id: "Cowbo Jones13",
    npc: "Cowbo Jones",
    world: 2,
    name: "Oh No, not the Elderly!",
  },
  {
    id: "Cowbo Jones14",
    npc: "Cowbo Jones",
    world: 2,
    name: "Tomb Raid",
  },
  {
    id: "Cowbo Jones15",
    npc: "Cowbo Jones",
    world: 2,
    name: "The New Sheriff",
  },
  {
    id: "Centurion1",
    npc: "Centurion",
    world: 2,
    name: "Down The Mimic Hole!",
  },
  {
    id: "Centurion2",
    npc: "Centurion",
    world: 2,
    name: "Which one of yous is the Mafia?",
  },
  {
    id: "Centurion3",
    npc: "Centurion",
    world: 2,
    name: "High Scorer",
  },
  {
    id: "Centurion4",
    npc: "Centurion",
    world: 2,
    name: "Colosseum Champ!",
  },
  {
    id: "Centurion5",
    npc: "Centurion",
    world: 2,
    name: "Colosseum GDQ",
  },
  {
    id: "Walupiggy1",
    npc: "Walupiggy",
    world: 2,
    name: "Treasure Hunt 1",
  },
  {
    id: "Walupiggy2",
    npc: "Walupiggy",
    world: 2,
    name: "Treasure Hunt 2",
  },
  {
    id: "Walupiggy3",
    npc: "Walupiggy",
    world: 2,
    name: "Treasure Hunt 3",
  },
  {
    id: "Walupiggy4",
    npc: "Walupiggy",
    world: 2,
    name: "Treasure Hunt 4",
  },
  {
    id: "Gangster Gus1",
    npc: "Gangster Gus",
    world: 2,
    name: "Plunderin Down Yonder",
  },
  {
    id: "Gangster Gus2",
    npc: "Gangster Gus",
    world: 2,
    name: "Perfect Progress Score",
  },
  {
    id: "Gangster Gus3",
    npc: "Gangster Gus",
    world: 2,
    name: "Sanke Revival Denial",
  },
];

const QuestsW3: Array<Quest> = [
  {
    id: "Iceland Irwin1",
    npc: "Iceland Irwin",
    world: 3,
    name: "Crikey, it's cold out!",
  },
  {
    id: "Hoggindaz1",
    npc: "Hoggindaz",
    world: 3,
    name: "Turn ON for what???",
  },
  {
    id: "Hoggindaz2",
    npc: "Hoggindaz",
    world: 3,
    name: "Trapping with the Lord",
  },
  {
    id: "Hoggindaz3",
    npc: "Hoggindaz",
    world: 3,
    name: "Constructing a Tower",
  },
  {
    id: "Hoggindaz4",
    npc: "Hoggindaz",
    world: 3,
    name: "Monke Tower Time!",
  },
  {
    id: "Hoggindaz5",
    npc: "Hoggindaz",
    world: 3,
    name: "Taking Samples",
  },
  {
    id: "Lonely Hunter1",
    npc: "Lonely Hunter",
    world: 3,
    name: "Leaf Him Alone!",
  },
  {
    id: "Lonely Hunter2",
    npc: "Lonely Hunter",
    world: 3,
    name: "Skeleton? Skelegone!",
  },
  {
    id: "Lord of the Hunt1",
    npc: "Lord of the Hunt",
    world: 3,
    name: "Pelt for the Pelt God",
  },
  {
    id: "Lord of the Hunt2",
    npc: "Lord of the Hunt",
    world: 3,
    name: "Frogecoin to the MOON!",
  },
  {
    id: "Lord of the Hunt3",
    npc: "Lord of the Hunt",
    world: 3,
    name: "Yet another Cartoon Reference",
  },
  {
    id: "Lord of the Hunt4",
    npc: "Lord of the Hunt",
    world: 3,
    name: "Small Stingers, Big Owie",
  },
  {
    id: "Lord of the Hunt5",
    npc: "Lord of the Hunt",
    world: 3,
    name: "The Mouse n the Molerat",
  },
  {
    id: "Lord of the Hunt6",
    npc: "Lord of the Hunt",
    world: 3,
    name: "Happy Tree Friend",
  },
  {
    id: "Lord of the Hunt7",
    npc: "Lord of the Hunt",
    world: 3,
    name: "Noot Noot!",
  },
  {
    id: "Lord of the Hunt8",
    npc: "Lord of the Hunt",
    world: 3,
    name: "Bunny you Should Say That!",
  },
  {
    id: "Lord of the Hunt9",
    npc: "Lord of the Hunt",
    world: 3,
    name: "Rollin' Thunder!",
  },
  {
    id: "Lord of the Hunt10",
    npc: "Lord of the Hunt",
    world: 3,
    name: "Untitled Quest",
  },
  {
    id: "Lord of the Hunt11",
    npc: "Lord of the Hunt",
    world: 3,
    name: "To Trap or not to Trap",
  },
  {
    id: "Snouts1",
    npc: "Snouts",
    world: 3,
    name: "A Salty Fall",
  },
  {
    id: "Snouts2",
    npc: "Snouts",
    world: 3,
    name: "Gravity VS Salt",
  },
  {
    id: "Snouts3",
    npc: "Snouts",
    world: 3,
    name: "Big Ol Chonker",
  },
];

export const AllQuests = [...QuestsW1, ...QuestsW2, ...QuestsW3];
